# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a7f772d97dff8489693426746f7532bce49b267e5132ef892068d34b7f1eef0580426046f4847f58eb333c771f5391800faa8466b1f2ebef3a82d9337098603

test:
  secret_key_base: cc5e847b27d4d6c0f10c5af1a236e2cea92d69776516be0aa91e526e9fcbe73fbf0d8b5771d6f143d0c5afaecd5b3164fa18bf1a7e21f7d38dae435c75c200ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
